### ISSUE TITLE
Pydantic error when listing tailnet devices: "Input should be a valid dictionary or instance of ClientConnectivity"

### ISSUE THREAD

**Issue by heretic098** [frenck/python-tailscale#884]
# Problem/Motivation

This morning I am getting an error from python-tailscale when listing tailnet devices:

```
Traceback (most recent call last):
  File "script.py", line 20, in ts_devices
    devices = await tailscale.devices()
  File "/home/heretic098/anaconda3/lib/python3.9/site-packages/tailscale/tailscale.py", line 116, in devices
    return Devices.parse_obj(data).devices
  File "/home/heretic098/anaconda3/lib/python3.9/site-packages/typing_extensions.py", line 2360, in wrapper
    return arg(*args, **kwargs)
  File "/home/heretic098/anaconda3/lib/python3.9/site-packages/pydantic/main.py", line 945, in parse_obj
    return cls.model_validate(obj)
  File "/home/heretic098/anaconda3/lib/python3.9/site-packages/pydantic/main.py", line 480, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 1 validation error for Devices
devices.4935547714179711.clientConnectivity
  Input should be a valid dictionary or instance of ClientConnectivity [type=model_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.0.3/v/model_type
````

Checking the response from the tailscale API shows that they have stopped including the ClientConnectivity details in the output of the request.

## Expected behavior

To get a list of devices

## Actual behavior

I get the error message detailed above

## Steps to reproduce

I suspect most scripts relying on this module are busted like this this morning.

## Proposed changes

As a quick fix, I tried substitiuting line 56 in `src/tailscale/models.py` with this:

```
    client_connectivity: Optional[ClientConnectivity] = Field(alias="clientConnectivity")
```

which works for me on my local system and allows the module to list devices again.

I recall seeing something in the tailscale API repo saying that the intention was to remove the clientconnectivity details from the response but I cannot find it now. If you want, I'm happy to submit a PR with the above change.

**Comment by heretic098** [comment]
This does not appear to be an issue this morning although the clientconnectivity information is still missing from the API response. Clearly I don't understand what is going on.

**Comment by frenck** [comment]
I'm sorry, but this library doesn't use Pydantic anymore. Please make sure you are using the latest version.

../Frenck
