### ISSUE TITLE
Obtain Device Status

### ISSUE THREAD

**Issue by Cyber5imon** [frenck/python-tailscale#915]
# Problem/Motivation

Looking to receive the status of the devices.

## Expected behavior

`devices[id].status` returns up or down

## Actual behavior

There is no status property

## Steps to reproduce

```
devices = await tailscale.devices()
    for device in devices:
        device_status = devices[device].status
```

## Proposed changes

Return if the device is online/offline

**Comment by Cyber5imon** [comment]
Looks like this may not yet be possible:
https://github.com/tailscale/tailscale/issues/7004

Can you think of any clever workarounds other than `ping`? Something that could be embedded in this package?

**Comment by frenck** [comment]
> Can you think of any clever workarounds other than ping?

That is not in scope for this package. If you want to ping a device, I suggest to look for a package that can ping an address.

../Frenck
